const fs = require('fs');

// 1. protect-pdf
let content = fs.readFileSync('app/protect-pdf/page.tsx', 'utf8');
content = content.replace('{!file ? (', '{resultUrl ? (\n                <div className="flex flex-col items-center justify-center gap-6 py-8">\n                    <div className="flex h-24 w-24 items-center justify-center rounded-full bg-green-100 text-green-500 dark:bg-green-900/30 dark:text-green-400">\n                        <Lock className="h-12 w-12" />\n                    </div>\n                    <div className="text-center">\n                        <h3 className="text-2xl font-bold text-zinc-900 dark:text-white">PDF Protected Successfully!</h3>\n                        <p className="mt-2 text-zinc-500 dark:text-zinc-400">\n                            Your file has been encrypted with the password.\n                        </p>\n                    </div>\n                    <div className="flex flex-col sm:flex-row gap-4 w-full max-w-md mt-4">\n                        <button\n                            onClick={() => {\n                                const link = document.createElement("a");\n                                link.href = resultUrl;\n                                link.download = resultFileName;\n                                document.body.appendChild(link);\n                                link.click();\n                                document.body.removeChild(link);\n                            }}\n                            className="flex-1 rounded-xl bg-green-500 px-4 py-3 text-sm font-semibold text-white shadow-sm hover:bg-green-600 transition-colors"\n                        >\n                            Download PDF\n                        </button>\n                        <button\n                            onClick={() => {\n                                URL.revokeObjectURL(resultUrl);\n                                setResultUrl(null);\n                                setResultFileName("");\n                            }}\n                            className="flex-1 rounded-xl bg-zinc-800 px-4 py-3 text-sm font-semibold text-white hover:bg-zinc-700 dark:bg-zinc-800 dark:text-white dark:hover:bg-zinc-700 transition-colors"\n                        >\n                            Protect Another\n                        </button>\n                    </div>\n                </div>\n            ) : !file ? (');
fs.writeFileSync('app/protect-pdf/page.tsx', content);

// 2. unlock-pdf
content = fs.readFileSync('app/unlock-pdf/page.tsx', 'utf8');
content = content.replace('{!file ? (', '{resultUrl ? (\n                <div className="flex flex-col items-center justify-center gap-6 py-8">\n                    <div className="flex h-24 w-24 items-center justify-center rounded-full bg-green-100 text-green-500 dark:bg-green-900/30 dark:text-green-400">\n                        <div className="text-4xl">🔓</div>\n                    </div>\n                    <div className="text-center">\n                        <h3 className="text-2xl font-bold text-zinc-900 dark:text-white">PDF Unlocked Successfully!</h3>\n                        <p className="mt-2 text-zinc-500 dark:text-zinc-400">\n                            Your file has been unlocked and restrictions removed.\n                        </p>\n                    </div>\n                    <div className="flex flex-col sm:flex-row gap-4 w-full max-w-md mt-4">\n                        <button\n                            onClick={() => {\n                                const link = document.createElement("a");\n                                link.href = resultUrl;\n                                link.download = resultFileName;\n                                document.body.appendChild(link);\n                                link.click();\n                                document.body.removeChild(link);\n                            }}\n                            className="flex-1 rounded-xl bg-green-500 px-4 py-3 text-sm font-semibold text-white shadow-sm hover:bg-green-600 transition-colors"\n                        >\n                            Download PDF\n                        </button>\n                        <button\n                            onClick={() => {\n                                URL.revokeObjectURL(resultUrl);\n                                setResultUrl(null);\n                                setResultFileName("");\n                            }}\n                            className="flex-1 rounded-xl bg-zinc-800 px-4 py-3 text-sm font-semibold text-white hover:bg-zinc-700 dark:bg-zinc-800 dark:text-white dark:hover:bg-zinc-700 transition-colors"\n                        >\n                            Unlock Another\n                        </button>\n                    </div>\n                </div>\n            ) : !file ? (');
fs.writeFileSync('app/unlock-pdf/page.tsx', content);

// 3. rotate-pdf
content = fs.readFileSync('app/rotate-pdf/page.tsx', 'utf8');
content = content.replace('{!file ? (', '{resultUrl ? (\n                <div className="flex flex-col items-center justify-center gap-6 py-8">\n                    <div className="flex h-24 w-24 items-center justify-center rounded-full bg-green-100 text-green-500 dark:bg-green-900/30 dark:text-green-400">\n                        <div className="text-4xl">🔄</div>\n                    </div>\n                    <div className="text-center">\n                        <h3 className="text-2xl font-bold text-zinc-900 dark:text-white">PDF Rotated Successfully!</h3>\n                        <p className="mt-2 text-zinc-500 dark:text-zinc-400">\n                            Your file has been rotated and saved.\n                        </p>\n                    </div>\n                    <div className="flex flex-col sm:flex-row gap-4 w-full max-w-md mt-4">\n                        <button\n                            onClick={() => {\n                                const link = document.createElement("a");\n                                link.href = resultUrl;\n                                link.download = resultFileName;\n                                document.body.appendChild(link);\n                                link.click();\n                                document.body.removeChild(link);\n                            }}\n                            className="flex-1 rounded-xl bg-green-500 px-4 py-3 text-sm font-semibold text-white shadow-sm hover:bg-green-600 transition-colors"\n                        >\n                            Download PDF\n                        </button>\n                        <button\n                            onClick={() => {\n                                URL.revokeObjectURL(resultUrl);\n                                setResultUrl(null);\n                                setResultFileName("");\n                            }}\n                            className="flex-1 rounded-xl bg-zinc-800 px-4 py-3 text-sm font-semibold text-white hover:bg-zinc-700 dark:bg-zinc-800 dark:text-white dark:hover:bg-zinc-700 transition-colors"\n                        >\n                            Rotate Another\n                        </button>\n                    </div>\n                </div>\n            ) : !file ? (');
fs.writeFileSync('app/rotate-pdf/page.tsx', content);
